//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBiblioE.CrossCutting.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBiblioE.CrossCutting.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar {0}.
        /// </summary>
        public static string GridViewExtensions_Edit {
            get {
                return ResourceManager.GetString("GridViewExtensions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover {0}.
        /// </summary>
        public static string GridViewExtensions_Remove {
            get {
                return ResourceManager.GetString("GridViewExtensions_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_edit_16_16 {
            get {
                object obj = ResourceManager.GetObject("icon_edit_16_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_Film_64_64 {
            get {
                object obj = ResourceManager.GetObject("icon_Film_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_Genre_64_64 {
            get {
                object obj = ResourceManager.GetObject("icon_Genre_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_Language_64_64 {
            get {
                object obj = ResourceManager.GetObject("icon_Language_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_message_alert_yellow_128_28 {
            get {
                object obj = ResourceManager.GetObject("icon_message_alert_yellow_128_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_message_close_rede_128_128 {
            get {
                object obj = ResourceManager.GetObject("icon_message_close_rede_128_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_message_confirm_blue_128_128 {
            get {
                object obj = ResourceManager.GetObject("icon_message_confirm_blue_128_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_message_ok_green_128_128 {
            get {
                object obj = ResourceManager.GetObject("icon_message_ok_green_128_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_trash_16_16 {
            get {
                object obj = ResourceManager.GetObject("icon_trash_16_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Language_Module {
            get {
                return ResourceManager.GetString("Language_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string LanguageViewModel_Code {
            get {
                return ResourceManager.GetString("LanguageViewModel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string LanguageViewModel_LanguageId {
            get {
                return ResourceManager.GetString("LanguageViewModel_LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LanguageViewModel_Name {
            get {
                return ResourceManager.GetString("LanguageViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiblioE - Confirmação.
        /// </summary>
        public static string MessageScreenTitleConfirm {
            get {
                return ResourceManager.GetString("MessageScreenTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiblioE - Erro.
        /// </summary>
        public static string MessageScreenTitleError {
            get {
                return ResourceManager.GetString("MessageScreenTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiblioE - Successo.
        /// </summary>
        public static string MessageScreenTitleSucess {
            get {
                return ResourceManager.GetString("MessageScreenTitleSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} salvo com sucesso!.
        /// </summary>
        public static string MSG_Success_Saved {
            get {
                return ResourceManager.GetString("MSG_Success_Saved", resourceCulture);
            }
        }
    }
}
