// <auto-generated />
namespace ProjectBiblioE.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201702052055272_DbInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
